name: lint and test code

on:
    push 

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '18.x'
            - run: yarn install --lockfile
            - run: yarn lint:check
            - run: yarn test
            - run: yarn build
